import { DataTypes } from 'sequelize';
import sequelize from '../../db';

export const Topic = sequelize.define('topic', {
	id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
	en: { type: DataTypes.STRING, allowNull: false },
	ru: { type: DataTypes.STRING, allowNull: false },
});

export const topicArray = [
	{ en: 'Books', ru: 'Книги' },
	{ en: 'Coins', ru: 'Монеты' },
	{ en: 'Stamps', ru: 'Марки' },
	{ en: 'Postcards', ru: 'Открытки' },
	{ en: 'Comics', ru: 'Комиксы' },
	{ en: 'Action Figures', ru: 'Фигурки' },
	{ en: 'Trading Cards', ru: 'Коллекционные карточки' },
	{ en: 'Vinyl Records', ru: 'Виниловые пластинки' },
	{ en: 'Movie Memorabilia', ru: 'Сувениры из фильмов' },
	{ en: 'Sports Jerseys', ru: 'Спортивные майки' },
	{ en: 'Autographs', ru: 'Автографы' },
	{ en: 'Art Prints', ru: 'Художественные печати' },
	{ en: 'Antique Furniture', ru: 'Антикварная мебель' },
	{ en: 'Vintage Clothing', ru: 'Винтажная одежда' },
	{ en: 'Toy Cars', ru: 'Игрушечные машины' },
	{ en: 'Dolls', ru: 'Куклы' },
	{ en: 'Model Trains', ru: 'Модельные поезда' },
	{ en: 'Musical Instruments', ru: 'Музыкальные инструменты' },
	{ en: 'Movie Props', ru: 'Реквизит из фильмов' },
	{ en: 'Fine China', ru: 'Фарфор' },
	{ en: 'Wristwatches', ru: 'Наручные часы' },
	{ en: 'Jewelry', ru: 'Ювелирные изделия' },
	{ en: 'Comic Books', ru: 'Комиксы' },
	{ en: 'Bottles', ru: 'Бутылки' },
	{ en: 'Sports Memorabilia', ru: 'Спортивная меморабилия' },
	{ en: 'Board Games', ru: 'Настольные игры' },
	{ en: 'Vintage Cameras', ru: 'Винтажные камеры' },
	{ en: 'Sneakers', ru: 'Кроссовки' },
	{ en: 'Figurines', ru: 'Фигурки' },
	{ en: 'Vinyl Toys', ru: 'Виниловые игрушки' },
	{ en: 'Vintage Posters', ru: 'Винтажные постеры' },
	{ en: 'Concert Tickets', ru: 'Билеты на концерты' },
	{ en: 'Vintage Magazines', ru: 'Винтажные журналы' },
	{ en: 'Musical Records', ru: 'Музыкальные записи' },
	{ en: 'Action Cameras', ru: 'Экшн-камеры' },
	{ en: 'Snow Globes', ru: 'Снежные шары' },
	{ en: 'Candles', ru: 'Свечи' },
	{ en: 'Shot Glasses', ru: 'Стопки для водки' },
	{ en: 'Beer Steins', ru: 'Пивные кружки' },
	{ en: 'Vintage Maps', ru: 'Винтажные карты' },
	{ en: 'Pocket Knives', ru: 'Карманные ножи' },
	{ en: 'Keychains', ru: 'Брелоки' },
	{ en: 'Trading Pins', ru: 'Коллекционные значки' },
	{ en: 'Artifacts', ru: 'Артефакты' },
	{ en: 'Antique Clocks', ru: 'Антикварные часы' },
	{ en: 'Hats', ru: 'Шляпы' },
	{ en: 'Lighters', ru: 'Зажигалки' },
	{ en: 'Fountain Pens', ru: 'Перьевые ручки' },
	{ en: 'Vintage Telephones', ru: 'Винтажные телефоны' },
	{ en: 'Vinyl Music Albums', ru: 'Виниловые музыкальные альбомы' },
	{ en: 'Other', ru: 'Другое' },
];
